name: Create Win x64 build 😎

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions: write-all
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: AStartUnity

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          projectPath: AStartUnity
          allowDirtyBuild: true

      # Output
      - name: Zip build
        run: |
          zip -r StandaloneWindows64.zip build/StandaloneWindows64
          zip -r Addressables.zip AStartUnity/ServerData
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            StandaloneWindows64.zip
            Addressables.zip
